//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike_Jornal
    {
        public long Bike_Jornal_ID { get; set; }
        public string Bike_Plate { get; set; }
        public string Tody_Date_Time { get; set; }
        public string Deliver_return_Bike { get; set; }
        public string Deliver_get_Bike { get; set; }
        public string Bike_Km { get; set; }
        public string Bike_Current_Owner { get; set; }
        public string Comments { get; set; }
    }
}
