//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bussines_Customers
    {
        public long ID { get; set; }
        public string Bussines_Name { get; set; }
        public string Bussines_Phone { get; set; }
        public string Bussines_Mobile { get; set; }
        public string Bussines_Fax { get; set; }
        public string Bussines_Address { get; set; }
        public string Bussines_Owner { get; set; }
        public string Bussines_Ownre_Mobile { get; set; }
        public string Bussines_WorkingHouers { get; set; }
        public string Bussines_Type { get; set; }
        public string Bussines_LogoName { get; set; }
        public string Bussines_LogoType { get; set; }
        public byte[] Bussines_LogoData { get; set; }
        public string Bussines_CustomerAddDate { get; set; }
    }
}
