//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Weeles_100_DBEntities : DbContext
    {
        public Weeles_100_DBEntities()
            : base("name=Weeles_100_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bike_Jornal> Bike_Jornal { get; set; }
        public virtual DbSet<Bussines_Customers> Bussines_Customers { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Deliver_Joranl> Deliver_Joranl { get; set; }
        public virtual DbSet<Deliver_Person> Deliver_Person { get; set; }
        public virtual DbSet<GIS_Data> GIS_Data { get; set; }
        public virtual DbSet<Login_Users> Login_Users { get; set; }
        public virtual DbSet<Motor_Bike> Motor_Bike { get; set; }
        public virtual DbSet<Deliver_WH> Deliver_WH { get; set; }
    }
}
