//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver_WH
    {
        public int id { get; set; }
        public string Mobile { get; set; }
        public string Date { get; set; }
        public string ReportIn { get; set; }
        public string ReportOut { get; set; }
        public string Lng { get; set; }
        public string Lat { get; set; }
    }
}
