//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver_Person
    {
        public long Deliver_ID { get; set; }
        public string Deliver_FULLName { get; set; }
        public string Deliver_Blue_ID { get; set; }
        public string Deliver_Lic_ID { get; set; }
        public string Deliver_Lic_Expration_date { get; set; }
        public string Deliver_Birth_Date { get; set; }
        public string Deliver_Mobile { get; set; }
        public string Deliver_Phone { get; set; }
        public string Deliver_Address { get; set; }
        public string Deliver_Email { get; set; }
        public string Emrg_Contact_Name { get; set; }
        public string Emrg_Contact_Phone { get; set; }
        public string Emrg_Contact_Reletive { get; set; }
    }
}
