//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliver_Joranl
    {
        public long Deliver_Jornal_ID { get; set; }
        public string Deliver_Joranl_Source { get; set; }
        public string Deliver_Joranl_Destination { get; set; }
        public string Deliver_Joranl_Type { get; set; }
        public string Deliver_Joranl_Date { get; set; }
        public string Deliver_Joranl_Payment { get; set; }
        public string Deliver_Joranl_Deliver_Person { get; set; }
    }
}
