//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delivers_CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motor_Bike
    {
        public int Bike_Id { get; set; }
        public string Bike_Plate { get; set; }
        public string Bike_Model { get; set; }
        public string Bike_Color { get; set; }
        public string Year_of_Production { get; set; }
        public string Car_License_Name { get; set; }
        public string Car_License_Type { get; set; }
        public byte[] Car_License_Data { get; set; }
    }
}
