//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Deliver_CRM_Droid.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeliverCRMWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DeliverCRMWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDeliverMobileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportInWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportOutWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportSickWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportDayOffWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReportInWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReportOutWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReportSickWHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetReportDayOffWHOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DeliverCRMWebService() {
            this.Url = "http://soft.solveit.co.il:8081/delivercrmwebservice.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDeliverMobileCompletedEventHandler GetDeliverMobileCompleted;
        
        /// <remarks/>
        public event GetReportInWHCompletedEventHandler GetReportInWHCompleted;
        
        /// <remarks/>
        public event GetReportOutWHCompletedEventHandler GetReportOutWHCompleted;
        
        /// <remarks/>
        public event GetReportSickWHCompletedEventHandler GetReportSickWHCompleted;
        
        /// <remarks/>
        public event GetReportDayOffWHCompletedEventHandler GetReportDayOffWHCompleted;
        
        /// <remarks/>
        public event SetReportInWHCompletedEventHandler SetReportInWHCompleted;
        
        /// <remarks/>
        public event SetReportOutWHCompletedEventHandler SetReportOutWHCompleted;
        
        /// <remarks/>
        public event SetReportSickWHCompletedEventHandler SetReportSickWHCompleted;
        
        /// <remarks/>
        public event SetReportDayOffWHCompletedEventHandler SetReportDayOffWHCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeliverMobile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDeliverMobile(string _mobile) {
            object[] results = this.Invoke("GetDeliverMobile", new object[] {
                        _mobile});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeliverMobileAsync(string _mobile) {
            this.GetDeliverMobileAsync(_mobile, null);
        }
        
        /// <remarks/>
        public void GetDeliverMobileAsync(string _mobile, object userState) {
            if ((this.GetDeliverMobileOperationCompleted == null)) {
                this.GetDeliverMobileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeliverMobileOperationCompleted);
            }
            this.InvokeAsync("GetDeliverMobile", new object[] {
                        _mobile}, this.GetDeliverMobileOperationCompleted, userState);
        }
        
        private void OnGetDeliverMobileOperationCompleted(object arg) {
            if ((this.GetDeliverMobileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeliverMobileCompleted(this, new GetDeliverMobileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportInWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReportInWH(string _mobile, string _date) {
            object[] results = this.Invoke("GetReportInWH", new object[] {
                        _mobile,
                        _date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportInWHAsync(string _mobile, string _date) {
            this.GetReportInWHAsync(_mobile, _date, null);
        }
        
        /// <remarks/>
        public void GetReportInWHAsync(string _mobile, string _date, object userState) {
            if ((this.GetReportInWHOperationCompleted == null)) {
                this.GetReportInWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportInWHOperationCompleted);
            }
            this.InvokeAsync("GetReportInWH", new object[] {
                        _mobile,
                        _date}, this.GetReportInWHOperationCompleted, userState);
        }
        
        private void OnGetReportInWHOperationCompleted(object arg) {
            if ((this.GetReportInWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportInWHCompleted(this, new GetReportInWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportOutWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReportOutWH(string _mobile, string _date) {
            object[] results = this.Invoke("GetReportOutWH", new object[] {
                        _mobile,
                        _date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportOutWHAsync(string _mobile, string _date) {
            this.GetReportOutWHAsync(_mobile, _date, null);
        }
        
        /// <remarks/>
        public void GetReportOutWHAsync(string _mobile, string _date, object userState) {
            if ((this.GetReportOutWHOperationCompleted == null)) {
                this.GetReportOutWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportOutWHOperationCompleted);
            }
            this.InvokeAsync("GetReportOutWH", new object[] {
                        _mobile,
                        _date}, this.GetReportOutWHOperationCompleted, userState);
        }
        
        private void OnGetReportOutWHOperationCompleted(object arg) {
            if ((this.GetReportOutWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportOutWHCompleted(this, new GetReportOutWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportSickWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReportSickWH(string _mobile, string _date) {
            object[] results = this.Invoke("GetReportSickWH", new object[] {
                        _mobile,
                        _date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportSickWHAsync(string _mobile, string _date) {
            this.GetReportSickWHAsync(_mobile, _date, null);
        }
        
        /// <remarks/>
        public void GetReportSickWHAsync(string _mobile, string _date, object userState) {
            if ((this.GetReportSickWHOperationCompleted == null)) {
                this.GetReportSickWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportSickWHOperationCompleted);
            }
            this.InvokeAsync("GetReportSickWH", new object[] {
                        _mobile,
                        _date}, this.GetReportSickWHOperationCompleted, userState);
        }
        
        private void OnGetReportSickWHOperationCompleted(object arg) {
            if ((this.GetReportSickWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportSickWHCompleted(this, new GetReportSickWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportDayOffWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetReportDayOffWH(string _mobile, string _date) {
            object[] results = this.Invoke("GetReportDayOffWH", new object[] {
                        _mobile,
                        _date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportDayOffWHAsync(string _mobile, string _date) {
            this.GetReportDayOffWHAsync(_mobile, _date, null);
        }
        
        /// <remarks/>
        public void GetReportDayOffWHAsync(string _mobile, string _date, object userState) {
            if ((this.GetReportDayOffWHOperationCompleted == null)) {
                this.GetReportDayOffWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportDayOffWHOperationCompleted);
            }
            this.InvokeAsync("GetReportDayOffWH", new object[] {
                        _mobile,
                        _date}, this.GetReportDayOffWHOperationCompleted, userState);
        }
        
        private void OnGetReportDayOffWHOperationCompleted(object arg) {
            if ((this.GetReportDayOffWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportDayOffWHCompleted(this, new GetReportDayOffWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetReportInWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetReportInWH(string _mobile, string _date, string _reportIn, string _reportAbsence, string _lng, string _lat) {
            object[] results = this.Invoke("SetReportInWH", new object[] {
                        _mobile,
                        _date,
                        _reportIn,
                        _reportAbsence,
                        _lng,
                        _lat});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetReportInWHAsync(string _mobile, string _date, string _reportIn, string _reportAbsence, string _lng, string _lat) {
            this.SetReportInWHAsync(_mobile, _date, _reportIn, _reportAbsence, _lng, _lat, null);
        }
        
        /// <remarks/>
        public void SetReportInWHAsync(string _mobile, string _date, string _reportIn, string _reportAbsence, string _lng, string _lat, object userState) {
            if ((this.SetReportInWHOperationCompleted == null)) {
                this.SetReportInWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReportInWHOperationCompleted);
            }
            this.InvokeAsync("SetReportInWH", new object[] {
                        _mobile,
                        _date,
                        _reportIn,
                        _reportAbsence,
                        _lng,
                        _lat}, this.SetReportInWHOperationCompleted, userState);
        }
        
        private void OnSetReportInWHOperationCompleted(object arg) {
            if ((this.SetReportInWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReportInWHCompleted(this, new SetReportInWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetReportOutWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetReportOutWH(string _mobile, string _date, string _reportOut, string _reportAbsence, string _lng, string _lat) {
            object[] results = this.Invoke("SetReportOutWH", new object[] {
                        _mobile,
                        _date,
                        _reportOut,
                        _reportAbsence,
                        _lng,
                        _lat});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetReportOutWHAsync(string _mobile, string _date, string _reportOut, string _reportAbsence, string _lng, string _lat) {
            this.SetReportOutWHAsync(_mobile, _date, _reportOut, _reportAbsence, _lng, _lat, null);
        }
        
        /// <remarks/>
        public void SetReportOutWHAsync(string _mobile, string _date, string _reportOut, string _reportAbsence, string _lng, string _lat, object userState) {
            if ((this.SetReportOutWHOperationCompleted == null)) {
                this.SetReportOutWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReportOutWHOperationCompleted);
            }
            this.InvokeAsync("SetReportOutWH", new object[] {
                        _mobile,
                        _date,
                        _reportOut,
                        _reportAbsence,
                        _lng,
                        _lat}, this.SetReportOutWHOperationCompleted, userState);
        }
        
        private void OnSetReportOutWHOperationCompleted(object arg) {
            if ((this.SetReportOutWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReportOutWHCompleted(this, new SetReportOutWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetReportSickWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetReportSickWH(string _mobile, string _date, string _reportIn, string _reportOut, string _reportAbsence, string _lng, string _lat) {
            object[] results = this.Invoke("SetReportSickWH", new object[] {
                        _mobile,
                        _date,
                        _reportIn,
                        _reportOut,
                        _reportAbsence,
                        _lng,
                        _lat});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetReportSickWHAsync(string _mobile, string _date, string _reportIn, string _reportOut, string _reportAbsence, string _lng, string _lat) {
            this.SetReportSickWHAsync(_mobile, _date, _reportIn, _reportOut, _reportAbsence, _lng, _lat, null);
        }
        
        /// <remarks/>
        public void SetReportSickWHAsync(string _mobile, string _date, string _reportIn, string _reportOut, string _reportAbsence, string _lng, string _lat, object userState) {
            if ((this.SetReportSickWHOperationCompleted == null)) {
                this.SetReportSickWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReportSickWHOperationCompleted);
            }
            this.InvokeAsync("SetReportSickWH", new object[] {
                        _mobile,
                        _date,
                        _reportIn,
                        _reportOut,
                        _reportAbsence,
                        _lng,
                        _lat}, this.SetReportSickWHOperationCompleted, userState);
        }
        
        private void OnSetReportSickWHOperationCompleted(object arg) {
            if ((this.SetReportSickWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReportSickWHCompleted(this, new SetReportSickWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetReportDayOffWH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SetReportDayOffWH(string _mobile, string _date, string _reportIn, string _reportOut, string _reportAbsence, string _lng, string _lat) {
            object[] results = this.Invoke("SetReportDayOffWH", new object[] {
                        _mobile,
                        _date,
                        _reportIn,
                        _reportOut,
                        _reportAbsence,
                        _lng,
                        _lat});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SetReportDayOffWHAsync(string _mobile, string _date, string _reportIn, string _reportOut, string _reportAbsence, string _lng, string _lat) {
            this.SetReportDayOffWHAsync(_mobile, _date, _reportIn, _reportOut, _reportAbsence, _lng, _lat, null);
        }
        
        /// <remarks/>
        public void SetReportDayOffWHAsync(string _mobile, string _date, string _reportIn, string _reportOut, string _reportAbsence, string _lng, string _lat, object userState) {
            if ((this.SetReportDayOffWHOperationCompleted == null)) {
                this.SetReportDayOffWHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetReportDayOffWHOperationCompleted);
            }
            this.InvokeAsync("SetReportDayOffWH", new object[] {
                        _mobile,
                        _date,
                        _reportIn,
                        _reportOut,
                        _reportAbsence,
                        _lng,
                        _lat}, this.SetReportDayOffWHOperationCompleted, userState);
        }
        
        private void OnSetReportDayOffWHOperationCompleted(object arg) {
            if ((this.SetReportDayOffWHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetReportDayOffWHCompleted(this, new SetReportDayOffWHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetDeliverMobileCompletedEventHandler(object sender, GetDeliverMobileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeliverMobileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeliverMobileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetReportInWHCompletedEventHandler(object sender, GetReportInWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportInWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportInWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetReportOutWHCompletedEventHandler(object sender, GetReportOutWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportOutWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportOutWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetReportSickWHCompletedEventHandler(object sender, GetReportSickWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportSickWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportSickWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GetReportDayOffWHCompletedEventHandler(object sender, GetReportDayOffWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportDayOffWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportDayOffWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetReportInWHCompletedEventHandler(object sender, SetReportInWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReportInWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReportInWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetReportOutWHCompletedEventHandler(object sender, SetReportOutWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReportOutWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReportOutWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetReportSickWHCompletedEventHandler(object sender, SetReportSickWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReportSickWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReportSickWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SetReportDayOffWHCompletedEventHandler(object sender, SetReportDayOffWHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetReportDayOffWHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetReportDayOffWHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591